name: ci
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change Directory
        run: cd ConcordiaMaps

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Format Code
        run: npx prettier --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change Directory
        run: cd ConcordiaMaps
        
      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Format Code
        run: npx prettier --check .

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Deploy to GitHub Pages
        run: echo "Deploy"
